name: $(Build.DefinitionName)_$(versionNumberPrefix).$(Build.BuildId)

trigger:
  - master

- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: heartland-react/heartland-react
