name: $(Build.DefinitionName)_$(versionNumberPrefix).$(Build.BuildId)

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  nodeVersion: "10.x"
  versionNumberPrefix: "1.1" #npm uses 3 digit build numbers
  fullVersionNumber: "$(versionNumberPrefix).$(Build.BuildId)"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: Install Node.js

  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: "(Get-Content './package.json').replace('9.9.9', '$(fullVersionNumber)') | Set-Content './package.json'"
    displayName: Replace Version Number Token

  - task: Npm@1
    inputs:
      command: publish
      publishRegistry: useFeed
      publishFeed: Edge Billing and Payments/heartland-react
