name: $(Build.DefinitionName)_$(versionNumberPrefix).$(Build.BuildId)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables: 
  fullVersionNumber: '$(versionNumberPrefix).$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job:
    steps:
    - script: npm run publish:npm

    - script: npm version patch

    - task: Npm@1
      displayName: 'Publish to npm Feed'
      inputs:
        command: publish
        publishRegistry: useFeed
        publishFeed: heartland-react/heartland-react